name: Build bmdsmdconvert

on:
  workflow_dispatch: # 手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bmdsmdconvert
          path: build/libs/*all.jar
